FROM alpine:<%= image.version %>

<%= snippet('labels', binding) -%>

<%= snippet('docker-entrypoint', binding) -%>

<%= snippet('dockerize', binding) -%>

<%= snippet('tini', binding) -%>

RUN apk --update add git git-lfs rsync less openssh vim && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

VOLUME /git
WORKDIR /git

ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]
CMD [ "git", "--help" ]
